services:
  flask-app:
    build: .
    container_name: cis4930-flask-app
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: cis4930-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - flask-app